language: node_js
node_js:
  - "10"
cache:
  yarn: true
  directories:
    - node_modules
before_script:
  - echo "$(which google-chrome-stable)"
  - export CHROME_PATH="$(which google-chrome-stable)"
  - sh -e /etc/init.d/xvfb start

script:
  - yarn build
  - yarn test:perf
addons:
  chrome: stable